apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-demo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:
    repoURL: 'https://github.com/ninjainkognito/homelab'
    targetRevision: HEAD
    path: kustomize-demo

  project: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
