apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: pihole
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.27.0

    helm:
      valueFiles:
        - $values/apps/pihole/values.yaml

  sources:
    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      targetRevision: 2.27.0

      helm:
        valueFiles:
          - $values/apps/pihole/values.yaml

    - repoURL: https://github.com/ninjainkognito/homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: pihole

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
